apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: busybox-daemon
spec:
  selector:
    matchLabels:
      app: busybox-daemon
  template:
    metadata:
      labels:
        app: busybox-daemon
    spec:
      containers:
        - name: busybox
          image: busybox:stable
          command: ["sh", "-c", "while true; do echo Hello from $(hostname); sleep 60; done"]