apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-config-map
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cm-test
  template:
    metadata:
      labels:
        app: cm-test
    spec:
      containers:
        - name: tester
          image: busybox:1.36
          command: ["sh","-c","sleep 3600"]
          envFrom:
            - configMapRef:
                name: app-config-map