apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-secret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-test
  template:
    metadata:
      labels:
        app: secret-test
    spec:
      containers:
        - name: tester
          image: busybox:1.36
          command: ["sh","-c","sleep 3600"]
          volumeMounts:
            - name: secret-vol
              mountPath: /etc/secrets
              readOnly: true
      volumes:
        - name: secret-vol
          secret:
            secretName: db-secret