apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-writer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-writer
  template:
    metadata:
      labels:
        app: log-writer
    spec:
      containers:
        - name: writer
          image: busybox:1.36
          command:
            - sh
            - -c
            - "mkdir -p /data && while true; do date >> /data/log.txt; sleep 5; done"
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: logs-pvc