apiVersion: v1
kind: Pod
metadata:
  name: nginx-req300-limit200
  namespace: quota-lab
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests:
          memory: 300Mi
        limits:
          memory: 200Mi