apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limits
  namespace: quota-lab
spec:
  limits:
    - type: Container
      min:
        memory: 100Mi
      max:
        memory: 300Mi
      default:
        memory: 200Mi
      defaultRequest:
        memory: 200Mi