apiVersion: batch/v1
kind: CronJob
metadata:
  name: log-time-cron-1
spec:
  schedule: "*/1 * * * *"   # Каждую минуту
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 1
      activeDeadlineSeconds: 20
      template:
        spec:
          containers:
            - name: logger
              image: busybox:stable
              command: ["sh", "-c", "echo $(date) Hello from $(hostname)"]
          restartPolicy: Never